/**
 * Column header / metric labels from the Fund Intelligence Metrics Knowledge Base.
 * Source: https://github.com/Bayardo88/scalar-ai-design-system / src/components/knowledgeBaseMetrics.ts
 */

export const KNOWLEDGE_BASE_METRICS = {
  // Company General Fields
  companyName: 'Company Name',
  funds: 'Fund(s)',
  capTableCurrency: 'Cap Table Currency',
  financialsCurrency: 'Financials Currency',
  fiscalYearEnd: 'Fiscal Year End',
  website: 'Website',
  legalCompanyName: 'Legal Company Name',
  firmsCategorization: "Firm's Categorization (tag)",
  industry: 'Industry',
  capitalIQId: 'Capital IQ ID',
  capitalIQDescription: 'Capital IQ Description',
  noticeZanbatoId: 'Notice.co/Zanbato some other Private Company ID',
  // Measurement Date / Cap Table
  valuationDate: 'Valuation Date (company measurement date)',
  capTableVersionName: 'Cap Table Version Name',
  totalOutstandingShares: 'Total Outstanding Shares (#)',
  totalFullyDilutedShares: 'Total Fully Diluted Shares (#)',
  initialInvestmentDate: 'Initial Investment Date',
  totalPreferredRounds: 'Total number of preferred rounds',
  mostRecentInvestmentDate: 'Most Recent Investment Date',
  totalOptions: 'Total Options (#)',
  averageOptionStrikePrice: 'Average Option Strike Price ($)',
  percentOptionPoolFullyDiluted: 'Percent Option Pool of total fully diluted shares (%)',
  totalWarrants: 'Total Warrants (#)',
  averageWarrantStrikePrice: 'Average Warrant Strike Price ($)',
  totalUnissuedOptions: 'Total Unissued Options (#)',
  totalCommonShares: 'Total Common Shares (#)',
  totalOutstandingPreferredShares: 'Total Outstanding Preferred Shares (#)',
  totalFullyDilutedPreferredShares: 'Total Fully Diluted Preferred Shares (#)',
  totalRaised: 'Total Raised',
  totalInitialLiquidationPreference: 'Total Initial Liquidation Preference ($)',
  totalPreferenceWithDividends: 'Total Preference (with Dividends) ($)',
  initialNoteIssuanceDate: 'Initial Note Issuance Date',
  initialNoteConversionModel: 'Initial Note Conversion Model (preferred, common, loan)',
  initialNoteConversionPricePerShare: 'Initial Note Conversion Price/Share ($)',
  initialNoteExpectedShares: 'Initial Note Expected Shares (#)',
  totalNoteExpectedShares: 'Total Note Expected Shares (#)',
  // Fund Ownership
  initialInvestment: 'Initial Investment',
  mostRecentInvestment: 'Most Recent Investment',
  fullyDilutedOwnership: 'Fully Diluted Ownership (%)',
  outstandingOwnership: 'Outstanding Ownership (%)',
  investedCapital: 'Invested Capital ($)',
  shares: 'Shares (#)',
  cseShares: 'CSE Shares (#)',
  securityId: 'Security ID',
  cashDistributions: 'Cash Distributions ($)',
  proceedsFromSharesSold: 'Proceeds from Shares Sold ($)',
  loanValue: 'Loan Value ($)',
  // Breakpoint Analysis
  usesCustomBreakpoints: 'Uses Custom Breakpoints (bool)',
  highestBreakpointPricePerCommonShare: 'Highest Breakpoint Price per Common Share ($)',
  highestBreakpointLimit: 'Highest Breakpoint limit ($)',
  // Cash Flows
  grossIRR: 'Gross IRR (%)',
  netCashFlows: 'Net Cash Flows ($)',
  totalOtherCapitalCosts: 'Total Other Capital Costs ($)',
  // Financials
  financialsDate: 'Financials Date (date)',
  ltmDate: 'LTM Date',
  ntmDate: 'NTM Date',
  balanceSheetAsOfDate: 'Balance Sheet As Of Date',
  ltmOrNtm: 'LTM or NTM',
  totalRevenue: 'Total Revenue ($)',
  totalCostOfSales: 'Total Cost of Sales ($)',
  grossProfit: 'Gross Profit ($)',
  operatingExpenses: 'Operating Expenses ($)',
  ebitda: 'EBITDA ($)',
  adjustedEbitda: 'Adjusted EBITDA ($)',
  depreciationExpense: 'Depreciation Expense ($)',
  amortizationExpense: 'Amortization Expense ($)',
  ebit: 'EBIT ($)',
  interestExpense: 'Interest Expense ($)',
  otherExpense: 'Other Expense ($)',
  pretaxIncome: 'Pretax Income ($)',
  incomeTaxes: 'Income Taxes ($)',
  netIncome: 'Net Income ($)',
  revenueGrowthRate: 'Revenue Growth Rate (%)',
  costOfSalesPercent: 'Cost of Sales (%)',
  grossMargin: 'Gross Margin (%)',
  operatingPercentOfSales: 'Operating % of Sales (%)',
  ebitdaMargin: 'EBITDA Margin (%)',
  adjustedEbitdaMargin: 'Adjusted EBITDA Margin (%)',
  netProfitMargin: 'Net Profit Margin (%)',
  // Balance Sheet - LTM
  cashAndEquivalents: 'Cash and Equivalents',
  accountsReceivables: 'Accounts Receivables',
  inventory: 'Inventory',
  otherCurrentAssets: 'Other Current Assets',
  totalCurrentAssets: 'Total Current Assets',
  ppe: 'PPE',
  intangibles: 'Intangibles',
  otherLongTermAssets: 'Other Long Term Assets',
  totalLongTermAssets: 'Total Long Term Assets',
  totalAssets: 'Total Assets',
  shortTermDebt: 'Short Term Debt',
  accountsPayable: 'Accounts Payable',
  accruedLiabilities: 'Accrued Liabilities',
  deferredRevenue: 'Deferred Revenue',
  otherCurrentLiabilities: 'Other Current Liabilities',
  totalCurrentLiabilities: 'Total Current Liabilities',
  longTermDebt: 'Long Term Debt',
  otherLongTermDebt: 'Other Long Term Debt',
  totalLongTermDebt: 'Total Long Term Debt',
  totalLiabilities: 'Total Liabilities',
  equity: 'Equity',
  totalLiabilitiesAndEquity: 'Total Liabilities and Equity',
  // Valuation/Allocation
  valuationStatus: 'Valuation Status (draft, published, final)',
  realizedValue: 'Realized Value ($)',
  unrealizedValue: 'Unrealized Value ($)',
  totalValue: 'Total Value ($)',
  moic: 'MOIC (x)',
  enterpriseValue: 'Enterprise Value',
  equityValue: 'Equity Value',
  breakevenEquityExitValue: 'Breakeven Equity Exit Value',
  valuationMethods: 'Valuation Methods (BV, PC, GT, etc)',
  allocationMethods: 'Allocation Methods (CSE, Waterfall, OPM, Backsolve, Future Exit, SSV)',
  impliedEvLtmRevenueMultiple: 'Implied EV/LTM Revenue Multiple (x)',
  impliedEvLtmEbitdaMultiple: 'Implied EV/LTM EBITDA Multiple (x)',
  impliedEvNtmMultiple: 'Implied EV/NTM Multiple (x)',
  impliedEvNtmEbitdaMultiple: 'Implied EV/NTM EBITDA Multiple (x)',
  impliedEvKpiMultiple: 'Implied EV/(KPI Metric) Multiple (x)',
  // GPC
  useMultiplePremiumDiscount: 'Use Multiple Premium Discount (bool)',
  useEquityValue: 'Use Equity Value (bool)',
  useCalculatedForwardMultiple: 'Use Calculated Forward Multiple (bool)',
  firstMultipleType: 'First Multiple Type (LTM, NTM or period year)',
  secondMultipleType: 'Second Multiple Type (LTM, NTM or period year)',
  ltmRevenueAppliedMultiple: 'LTM Revenue Applied Multiple (x)',
  ltmEbitdaAppliedMultiple: 'LTM EBITDA Applied Multiple (x)',
  ntmRevenueAppliedMultiple: 'NTM Revenue Applied Multiple (x)',
  ntmEbitdaAppliedMultiple: 'NTM EBITDA Applied Multiple (x)',
  weightedAppliedMultiple: 'Weighted Applied Multiple (x)',
  weightedEnterpriseValue: 'Weighted Enterprise Value ($)',
  weightedEquityValue: 'Weighed Equity Value ($)',
  percentileRanking: 'Percentile Ranking (%)',
  ltmRevenue: 'LTM Revenue',
  ltmRevenueGrowth: 'LTM Revenue Growth',
  ntmRevenue: 'NTM Revenue',
  ntmRevenueGrowth: 'NTM Revenue Growth',
  ltmEbitda: 'LTM EBITDA',
  ntmEbitda: 'NTM EBITDA',
  tangibleBookValue: 'Tangible Book Value',
  // Backsolve
  securityNames: 'Security Names (Series A, Series B)',
  targetTotalShares: 'Target Total Shares (#)',
  targetTotalValue: 'Target Total Value ($)',
  opmBacksolveDate: 'OPM Backsolve Date',
  opmVolatilitySelected: 'OPM Volatility Selected (%)',
  opmMaturity: 'OPM Maturity (#)',
  opmMaturityDate: 'OPM Maturity Date',
  opmRiskFreeRate: 'OPM Risk Free Rate (%)',
  impliedEquityValue: 'Implied Equity Value',
  usesMarketAdjustment: 'Uses Market Adjustment (bool)',
  marketAdjustmentAsOfDate: 'Market Adjustment As Of Date',
  metricBasisForAdjustment: 'Metric Basis for Adjustment (Market Cap, Enterprise Value, etc)',
  marketAdjustmentPercent: 'Market Adjustment (%)',
  adjustedEnterpriseValue: 'Adjusted Enterprise Value ($)',
  adjustedEquityValue: 'Adjusted Equity Value ($)',
  // DCF
  wacc: 'WACC (%)',
  effectiveTaxRate: 'Effective Tax Rate (%)',
  summedPvDiscretePeriodCashFlows: 'Summed Present Value of Discrete Period Cash Flows ($)',
  presentValueTerminalValue: 'Present Value of Terminal Value ($)',
  presentValueNolCarryforwards: 'Present Value of NOL Carryforwards ($)',
  // Calibration
  ltmRevenueMultiple: 'LTM Revenue Multiple',
  ntmRevenueMultiple: 'NTM Revenue Multiple',
  ltmRevenueMultiplePercentile: 'LTM Revenue Multiple Percentile',
  ntmRevenueMultiplePercentile: 'NTM Revenue Multiple Percentile',
  ltmRevenueMultiplePremium: 'LTM Revenue Multiple Premium',
  ntmRevenueMultiplePremium: 'NTM Revenue Multiple Premium',
  ltmEbitdaMultiple: 'LTM EBITDA Multiple',
  ntmEbitdaMultiple: 'NTM EBITDA Multiple',
  ltmEbitdaMultiplePercentile: 'LTM EBITDA Multiple Percentile',
  ntmEbitdaMultiplePercentile: 'NTM EBITDA Multiple Percentile',
  ltmEbitdaMultiplePremium: 'LTM EBITDA Multiple Premium',
  ntmEbitdaMultiplePremium: 'NTM EBITDA Multiple Premium',
  // Documents & Process Management
  totalNumberOfDocuments: 'Total Number of documents (#)',
  numberOfDocumentsReferenced: 'Number of documents referenced (#)',
  numberOfPendingDocumentRequests: 'Number of pending document requests (#)',
  numberOfPendingQuestions: 'Number of pending questions (#)',
} as const;

export type KnowledgeBaseMetricKey = keyof typeof KNOWLEDGE_BASE_METRICS;

export const KNOWLEDGE_BASE_METRIC_KEYS: KnowledgeBaseMetricKey[] = Object.keys(
  KNOWLEDGE_BASE_METRICS
) as KnowledgeBaseMetricKey[];

/** Categorized groups for display in the modal */
export const METRIC_CATEGORIES: { label: string; keys: KnowledgeBaseMetricKey[] }[] = [
  {
    label: 'Company General Fields',
    keys: ['companyName', 'funds', 'capTableCurrency', 'financialsCurrency', 'fiscalYearEnd', 'website', 'legalCompanyName', 'firmsCategorization', 'industry', 'capitalIQId', 'capitalIQDescription', 'noticeZanbatoId'],
  },
  {
    label: 'Measurement Date / Cap Table',
    keys: ['valuationDate', 'capTableVersionName', 'totalOutstandingShares', 'totalFullyDilutedShares', 'initialInvestmentDate', 'totalPreferredRounds', 'mostRecentInvestmentDate', 'totalOptions', 'averageOptionStrikePrice', 'percentOptionPoolFullyDiluted', 'totalWarrants', 'averageWarrantStrikePrice', 'totalUnissuedOptions', 'totalCommonShares', 'totalOutstandingPreferredShares', 'totalFullyDilutedPreferredShares', 'totalRaised', 'totalInitialLiquidationPreference', 'totalPreferenceWithDividends', 'initialNoteIssuanceDate', 'initialNoteConversionModel', 'initialNoteConversionPricePerShare', 'initialNoteExpectedShares', 'totalNoteExpectedShares'],
  },
  {
    label: 'Fund Ownership',
    keys: ['initialInvestment', 'mostRecentInvestment', 'fullyDilutedOwnership', 'outstandingOwnership', 'investedCapital', 'shares', 'cseShares', 'securityId', 'cashDistributions', 'proceedsFromSharesSold', 'loanValue'],
  },
  {
    label: 'Breakpoint Analysis',
    keys: ['usesCustomBreakpoints', 'highestBreakpointPricePerCommonShare', 'highestBreakpointLimit'],
  },
  {
    label: 'Cash Flows',
    keys: ['grossIRR', 'netCashFlows', 'totalOtherCapitalCosts'],
  },
  {
    label: 'Financials',
    keys: ['financialsDate', 'ltmDate', 'ntmDate', 'balanceSheetAsOfDate', 'ltmOrNtm', 'totalRevenue', 'totalCostOfSales', 'grossProfit', 'operatingExpenses', 'ebitda', 'adjustedEbitda', 'depreciationExpense', 'amortizationExpense', 'ebit', 'interestExpense', 'otherExpense', 'pretaxIncome', 'incomeTaxes', 'netIncome', 'revenueGrowthRate', 'costOfSalesPercent', 'grossMargin', 'operatingPercentOfSales', 'ebitdaMargin', 'adjustedEbitdaMargin', 'netProfitMargin'],
  },
  {
    label: 'Balance Sheet',
    keys: ['cashAndEquivalents', 'accountsReceivables', 'inventory', 'otherCurrentAssets', 'totalCurrentAssets', 'ppe', 'intangibles', 'otherLongTermAssets', 'totalLongTermAssets', 'totalAssets', 'shortTermDebt', 'accountsPayable', 'accruedLiabilities', 'deferredRevenue', 'otherCurrentLiabilities', 'totalCurrentLiabilities', 'longTermDebt', 'otherLongTermDebt', 'totalLongTermDebt', 'totalLiabilities', 'equity', 'totalLiabilitiesAndEquity'],
  },
  {
    label: 'Valuation / Allocation',
    keys: ['valuationStatus', 'realizedValue', 'unrealizedValue', 'totalValue', 'moic', 'enterpriseValue', 'equityValue', 'breakevenEquityExitValue', 'valuationMethods', 'allocationMethods', 'impliedEvLtmRevenueMultiple', 'impliedEvLtmEbitdaMultiple', 'impliedEvNtmMultiple', 'impliedEvNtmEbitdaMultiple', 'impliedEvKpiMultiple'],
  },
  {
    label: 'GPC / Transaction Comps',
    keys: ['useMultiplePremiumDiscount', 'useEquityValue', 'useCalculatedForwardMultiple', 'firstMultipleType', 'secondMultipleType', 'ltmRevenueAppliedMultiple', 'ltmEbitdaAppliedMultiple', 'ntmRevenueAppliedMultiple', 'ntmEbitdaAppliedMultiple', 'weightedAppliedMultiple', 'weightedEnterpriseValue', 'weightedEquityValue', 'percentileRanking', 'ltmRevenue', 'ltmRevenueGrowth', 'ntmRevenue', 'ntmRevenueGrowth', 'ltmEbitda', 'ntmEbitda', 'tangibleBookValue'],
  },
  {
    label: 'Backsolve / OPM',
    keys: ['securityNames', 'targetTotalShares', 'targetTotalValue', 'opmBacksolveDate', 'opmVolatilitySelected', 'opmMaturity', 'opmMaturityDate', 'opmRiskFreeRate', 'impliedEquityValue', 'usesMarketAdjustment', 'marketAdjustmentAsOfDate', 'metricBasisForAdjustment', 'marketAdjustmentPercent', 'adjustedEnterpriseValue', 'adjustedEquityValue'],
  },
  {
    label: 'DCF',
    keys: ['wacc', 'effectiveTaxRate', 'summedPvDiscretePeriodCashFlows', 'presentValueTerminalValue', 'presentValueNolCarryforwards'],
  },
  {
    label: 'Calibration',
    keys: ['ltmRevenueMultiple', 'ntmRevenueMultiple', 'ltmRevenueMultiplePercentile', 'ntmRevenueMultiplePercentile', 'ltmRevenueMultiplePremium', 'ntmRevenueMultiplePremium', 'ltmEbitdaMultiple', 'ntmEbitdaMultiple', 'ltmEbitdaMultiplePercentile', 'ntmEbitdaMultiplePercentile', 'ltmEbitdaMultiplePremium', 'ntmEbitdaMultiplePremium'],
  },
  {
    label: 'Documents & Process',
    keys: ['totalNumberOfDocuments', 'numberOfDocumentsReferenced', 'numberOfPendingDocumentRequests', 'numberOfPendingQuestions'],
  },
];
